#!/bin/zsh
export NODE_PATH=/home/jing/.local/share/pnpm/global/5/node_modules
export PYTHONPATH=$HOME/Documents/Project/qutebrowser
export MPV_COMMAND=/bin/mpv
export SWAYSOCK=/run/user/$(id -u)/sway-ipc.$(id -u).$(pgrep -x sway).sock
export QUTE_QT_WRAPPER=PyQt6
nohup python3 -m qutebrowser $@ 1>/dev/null 2>&1 &
