#! /bin/zsh

usrfile=$(mktemp -d)
cp -r $HOME/.wine/drive_c/users/$USER $usrfile
# regs=$(mktemp -d)
# cp $HOME/.wine/*.reg $regs
rm -rf $HOME/.wine
wine wineboot
# cp $regs/*.reg $HOME/.wine
rm -rf $HOME/.wine/dosdevices/z:
# For system-wise mono installation, one shouldn't remove z:
ln -sf $HOME/Archives/Games/GOG $HOME/.wine/drive_c/'GOG Games'
rm -rf $HOME/.wine/drive_c/users/$USER
cp -r $usrfile/$USER $HOME/.wine/drive_c/users
rm -rf $usrfile $regs

# winetricks d3dx11_43 d3dcompiler_43 d3dcompiler_47 d3dx9_43
