#!/bin/zsh
set -e
mail=jingmatrix@gmail.com
prenom=Jianyu
nom=MA
curl \
	-F id_article=1042 \
	-F id_formulaire=17 \
	-F page=article \
	-F formulaire_action=formidable \
	-F formulaire_action_args='dG/ndLrLo+gvGPVxR6SbFiaudrCtOraBqEzenxaYNIHb7oNgJV0IPGgbrzP1qbgSWzK9UdgrWLeplTcb15eIdbz+99Op7ltU7esE/YfJ' \
	-F formidable_afficher_apres=valeurs \
	-F mechantrobot='' \
	-F date_1=$(date -d ${1:-"1 day"} +%d/%m/%Y) \
	-F 'checkbox_2[]=choix1' \
	-F 'checkbox_1[]=7' \
	-F 'checkbox_2[]=choix2' \
	-F textarea_1=$nom \
	-F textarea_2=$prenom \
	-F selection_1=choix2 \
	-F textarea_3=$mail 'https://www.math.univ-toulouse.fr/spip.php?article1042&id_article=1042&id_formulaire=17' >/tmp/reservation.html
if sed '/Vous venez de valider/q1' /tmp/reservation.html -n; then
	echo Your code Failed
else
	echo 🎉🎉🎉🎉🎉🎉
fi
