#! /bin/zsh

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
folder="$HOME/Images/Papier Peint"
pic=$(ls "$folder"/* | shuf -n1)
gsettings set org.gnome.desktop.background picture-uri "file://$pic"
