#!/bin/zsh
# initial idea: Florian Bruhin (The-Compiler)
# author: Thore Bödecker (foxxx0) Jianyu MA

_proto_version=1
_ipc_socket="${XDG_RUNTIME_DIR}/qutebrowser/ipc-$(echo -n "$USER" | md5sum | cut -d' ' -f1)"
export PATH=$PATH:/home/jing/.nvm/versions/node/v17.4.0/bin
export NODE_PATH=/home/jing/.nvm/versions/node/v17.4.0/lib/node_modules
export PYTHONPATH=$HOME/Documents/Project/qutebrowser
export MPV_COMMAND=/bin/mpv

LD_PRELOAD=/usr/lib/x86_64-linux-gnu/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so

[[ $1 = -* ]] || search_text=$(echo -n $@)

if [[ -e ${_ipc_socket} && -n ${_args} ]]; then
	printf '{"args": ["%s"], "target_arg": null, "version": "%s", "protocol_version": %d, "cwd": "%s"}\n' \
		"${search_text}" \
		"${_qb_version}" \
		"${_proto_version}" \
		"${PWD}" | socat -lf /dev/null - UNIX-CONNECT:"${_ipc_socket}" &
elif [[ -z ${search_text} && -n $@ ]]; then
	python3 -m qutebrowser $@
else
	nohup python3 -m qutebrowser ${search_text} 2>/dev/null &
fi
