#! zsh

usrfile=$(mktemp -d)
cp -r $HOME/.wine/drive_c/users/$USER $usrfile
regs=$(mktemp -d)
cp $HOME/.wine/*.reg $regs
rm -rf $HOME/.wine
wine wineboot
cp $regs/*.reg $HOME/.wine
rm -rf $HOME/.wine/dosdevices/z:
ln -sf $HOME/Archives/Games/'GOG Games' $HOME/.wine/drive_c
rm -rf $HOME/.wine/drive_c/users/$USER
cp -r $usrfile/$USER $HOME/.wine/drive_c/users
rm -rf $usrfile $regs
winetricks d3dx11_43
winetricks d3dcompiler_43
