#!/data/data/com.termux/files/usr/bin/sh

ifconfig 2>/dev/null | grep 'inet 10.188' 1>/dev/null && ping -c 1 wireless.wifirst.net 2>/dev/null 1>/dev/null
if [ $? -eq 0 ]; then

	if [ -e $PREFIX/var/run/atd.pid ]; then
		kill -s 0 $(cat $PREFIX/var/run/atd.pid)
		if [ $? -ne 0 ]; then
			atd
		fi
	else
		atd
	fi

	path_to_current_script=/data/data/com.termux/files/home/.shortcuts/blaise_pascal
	atq -q n | cut -f 1 | xargs atrm

	curl -s 'https://wireless.wifirst.net/goform/HtmlLogout' \
		--data "error_url=https://www.google.fr" \
		--data "success_url=https://portal-front.wifirst.net"

	# Generate random account
	login_wifirst() {
		current_time=$(date +%s%3N)
		error_code=$(curl -s -D - 'https://wireless.wifirst.net/goform/HtmlLoginRequest' \
			--data "username=PAY/$current_time@wifirst.net" \
			--data "password=$current_time" \
			--data "success_url=https://www.google.fr" \
			--data "error_url=https://portal-front.wifirst.net" \
			--compressed | grep -o -P 'code=\K\d')
		return ${error_code:=0}
	}

	if ! login_wifirst; then
		termux-toast "Login failed, reset MAC address"
		su shell -c cmd wifi forget-network $(sudo cmd wifi status | grep -o -P 'Net ID: \K\d+')
		sudo cmd wifi connect-network 'Wifirst Blaise Pascal' open -r non_persistent
		sleep 8
		login_wifirst
	fi
	at -q n -M -f $path_to_current_script now + 10 minute

	if [ -e $PREFIX/var/lib/zerotier-one/zerotier-one.pid ]; then
		kill -s 0 $(cat $PREFIX/var/lib/zerotier-one/zerotier-one.pid)
		if [ $? -ne 0 ]; then
			sudo ip rule | grep 'lookup main' 1>/dev/null
			if [ $? -ne 0 ]; then
				sudo ip rule add from all table main
			fi
			sudo zerotier-one &
		fi
	else
		sudo ip rule | grep 'lookup main' 1>/dev/null
		if [ $? -ne 0 ]; then
			sudo ip rule add from all table main
		fi
		sudo zerotier-one &
	fi

	termux-wake-lock &
else
	termux-toast "Not connected to Wifirst Blaise Pascal"
	termux-wake-unlock
fi
