#! /bin/zsh
# This is NetworkManager Dispatcher script.
# It should be put in /etc/NetworkManager/dispatcher.d

if [[ $1 = wl* && $2 == 'dhcp4-change' ]]; then
	if [[ $CONNECTION_ID == 'ups' ]]; then
		function upslogin {
			ups=($(</home/jing/.config/ups))
			for portal in $portals; do
				url="https://$portal/index.php?zone=$zone"
				/bin/curl -f -s $url \
					-H "authority: $portal" \
					-H 'cache-control: max-age=0' \
					-H 'upgrade-insecure-requests: 1' \
					-H "origin: https://$portal" \
					-H 'content-type: application/x-www-form-urlencoded' \
					-H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36' \
					-H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
					-H 'accept-language: en-US,en;q=0.9' \
					-H 'dnt: 1' \
					-H 'sec-fetch-site: same-origin' \
					-H 'sec-fetch-mode: navigate' \
					-H 'sec-fetch-user: ?1' \
					-H 'sec-fetch-dest: document' \
					--data-raw "auth_user=$ups[1]&auth_pass=$ups[2]&redirurl=&accept=Connexion+%28Authentication%29" \
					--compressed >/dev/null && exit
			done
		}

		local -a portals=('wifi-gw2-ups.private.univ-tlse3.fr:8003')
		local zone='ssid_ups'
		upslogin
	elif [[ $CONNECTION_ID == "Wifirst Blaise Pascal" ]]; then
		su jing /home/jing/Documents/Code/Shell/scripts/blasie_pascal_wifi
	# elif
	# 	[[ $CONNECTION_ID == 'Here is MA' ]]
	# then
	# 	local -a portals=(
	# 		'pftf04.in.crous-toulouse.fr:8003'
	# 		'pftf01.in.crous-toulouse.fr:8003'
	# 		'pftf02.in.crous-toulouse.fr:8003'
	# 		'pftf03.in.crous-toulouse.fr:8003'
	# 	)
	# 	local zone='lan'
	# 	upslogin
	fi
fi
