mixed-port: 8080
allow-lan: false
mode: rule
proxies:
  - name: "i2pd"
    type: http
    server: localhost
    port: 4444
  - name: "tor"
    type: socks5
    server: localhost
    port: 9050
rules:
  - DOMAIN-SUFFIX,onion,tor
  - DOMAIN-SUFFIX,i2p,i2pd
