#! /bin/zsh

extension=${1:e}
cmd="echo"
if [[ $extension == "pdf" ]]; then
	cmd=/home/jing/Documents/Code/Shell/toc/bookmark-pdf
elif [[ $extension == "djvu" ]]; then
	cmd=/home/jing/Documents/Code/Shell/toc/bookmark-djvu
fi
$cmd $@
