#! /bin/zsh

extension=${1:e}
cmd="echo"
script_dir=${0:A:h}/../toc
if [[ $extension == "pdf" ]]; then
	cmd=$script_dir/bookmark-pdf
elif [[ $extension == "djvu" ]]; then
	cmd=$script_dir/bookmark-djvu
fi
$cmd $@
