#! /bin/sh

# Please change this variable accordingly.
path_to_current_script="$HOME/Documents/Code/Shell/scripts/blasie_pascal_wifi"
# To start the login process automatically once you are connected to the Wi-Fi,
# put the following commands into a script located at the directory /etc/NetworkManager/dispatcher.d/.
# Replace $USER and $path_to_current_script by correct values in current system.
# You might need to set $USER to be able to run the sudo commands in this script without password
# via `sudo visudo /etc/sudoers`.
#
# #! /bin/sh
# if [ $1 = 'wlp1s0' ] && [ $2 = 'dhcp4-change' ] &&
# 	[ $CONNECTION_ID = "Wifirst Blaise Pascal" ]; then
# 	su $USER $path_to_current_script
# fi

if [ "$(/sbin/iwgetid | grep 'ESSID:"Wifirst Blaise Pascal"')" ]; then

	# First logout from possible old sessions
	time_remaining=$(/bin/curl -s 'https://wireless.wifirst.net/captive-portal/api' -H "Content-Type: application/captive+json" | /bin/grep -oP '"seconds-remaining": \K\d+')
	if [ ${time_remaining:-0} -gt 10 ]; then
		/bin/atq -q n | /bin/cut -f 1 | /bin/xargs /bin/atrm
		/bin/at -q n -M -f $path_to_current_script now + $(expr $time_remaining / 60) minutes
		exit
	fi

	/bin/curl -s 'https://wireless.wifirst.net/goform/HtmlLogout' \
		--data "error_url=https://www.google.fr" \
		--data "success_url=https://portal-front.wifirst.net"

	# Generate random account

	current_time=$(date +%s%3N)
	error_code=$(/bin/curl -s -D - 'https://wireless.wifirst.net/goform/HtmlLoginRequest' \
		--data "username=PAY/$current_time@wifirst.net" \
		--data "password=$current_time" \
		--data "success_url=https://www.google.fr" \
		--data "error_url=https://portal-front.wifirst.net" \
		--compressed | /bin/grep -o -P 'code=\K\d')
	if [ ${error_code:-0} -eq 2 ]; then
		# notify-send "Wifi fails with code $error_code" "Attempt to change the mac address"
		dev=$(/bin/ip link | /bin/grep -o -P 'wl[^:]+')
		sudo /bin/ip link set $dev down
		sudo /bin/macchanger -r $dev
		sudo /bin/ip link set $dev up
		# Network dispatcher would run this script again
	else
		# remove possible duplicated at jobs
		/bin/atq -q n | /bin/cut -f 1 | /bin/xargs /bin/atrm
		# setup new job in 10 minutes
		/bin/at -q n -M -f $path_to_current_script now + 10 minutes
	fi
fi
