#! /bin/zsh

extension=${1:e}
cmd="echo"
script_dir=${0:A:h}/../bookmark

if [[ $extension == "pdf" ]]; then
	cmd=$script_dir/pdf_bookmark.py
	$cmd -p $1 > $2
elif [[ $extension == "djvu" ]]; then
	cmd=$script_dir/bookmark-djvu-extract
	$cmd $1 -o $2
fi
