#! /bin/zsh

if [[ $USER == "jing" ]]; then
	# update plugin install state
	BASEDIR=$(dirname "$0")
	echo "Updating plugin installed state"
	tree -L 3 $HOME/.local/share/nvim/site/pack >$BASEDIR/../nvim/vim.plugin
fi

# pull updates from remote repos
echo "Updating local git repository"

local project_dir=$HOME/Documents/Project
[[ -d $project_dir ]] || project_dir=$HOME/Project
[[ -d $project_dir ]] || exit

for d in $HOME/.local/share/nvim/site/pack/*/*/*/ $ZSH/custom/{plugin,theme}s/* $project_dir/*/; do
	[[ -d $d ]] && (
		cd "$d"
		if [[ -d .git ]]; then
			printf "\t\tEnter directory \e]8;;file://$PWD\e\\$PWD\e]8;;\e\\"
			printf "\n"
			git pull --rebase
		fi
	)
done
