#!/bin/zsh
# dependency:
# curl to download data
# jq (https://stedolan.github.io/jq/) to parse json data
# usage:
# ./upsCalendar.sh [duration of time, default is 3 days]
# for example, you can use:
# ./upsCalendar.sh "1week"
# optional you can set startdate manually as environment variable
# set zoom=1 to open zoon link possibly
set -e
if ! [[ -n $startdate ]]; then
	startdate=$(date -I)
fi
enddate=$(date -d ${startdate}' '${1:-"2days"} -I)
follow_courses="25"
# course=(
# 	"Holomorphic dynamics in dimension one : some advanced topics. (F. Berteloot and P.Roesch)"
# 	"Topics in Differential Complex Geometry (E. Legendre)"
# 	"Hamilton-Jacobi equations for biology (S. Mirrahimi)"
# 	"Stability analysis of ODE's or PDE's periodic solutions. Theoretical and numerical aspects. (P. Noble)"
# 	"Learning. (J. M. Loubes, B. Laurent-Bonneau)"
# "Lévy Processes (L. Huang)"
# )
# course=(
# 	"Complex analytic and differential geometry (V. Guedj)"
# 	"Hyperbolic manifolds (J.-P. Otal)"
# 	"Introduction to algebraic geometry (T. Dedieu)"
# 	"Elliptic PDEs and evolution problems (J. Fehrenbach et J. Royer)"
# 	"Convex Analysis / Optimisation and applications. (C. Dossal et P. Maréchal)"
# 	"Discretization of PDEs: \033[1;36m
# \t\t\tAnalysis and discretization of transport equations.(F. Boyer)
# \t\t\tConvergence of probability measures, functional limit theorems and applications. (R. Chhaibi)\033[0m"
	# "Convergence of probability measures, functional limit theorems and applications. (R. Chhaibi)"
	# "Stochastic calculus. (P. Maillard)"
	# "Asymptotic statistics and modeling. (P. Berthet)"
# )
course=(
	"Complex analytic and differential geometry (V. Guedj)"
	"Hyperbolic manifolds (J.-P. Otal)"
	"Introduction to differential and algebraic topology (T. Fiedler)"
	"Spectral theory (J. Royer)"
	"Elliptic PDEs and Calculus of Variations (R. Ignat)"
	"An introduction to the theoretical and numerical analysis of nonlinear conservation laws (F. Boyer)"
	"Convergence of probability measures, infinite dimensional limit theorems and optimal transport. (R. Chhaibi)"
	"Stochastic calculus. (L. Coutin)"
	"Asymptotic statistics and modeling. (P. Neuvial, F. Gamboa)"
	"Approximation of PDEs (G. Haine, D. Matignon, S. Pernet, M. Salaün)"
	"Advanced statistical methods (X. Gendre, F. Simatos)"
)
typeset -A zoomlink
zoomlink=(
	# DON'T change the order, it is hard-coded order
	# Complex Geometry Tuesday
	[2mar.]="zoommtg://univ-tlse3-fr.zoom.us/join?action=join&confno=89280020232&pwd=VFlhdFhyUTZZVFdOUnU2UzloTWVldz09"
	# Complex Geometry Friday
	[2ven.]="zoommtg://univ-tlse3-fr.zoom.us/join?action=join&confno=81369608657&pwd=R1oxUSsxRWY5d3QvNXpWYmlvZ0VKUT09"
	# Reading seminar
	[1seminar]="zoommtg://univ-tlse3-fr.zoom.us/join?action=join&confno=81923444202&pwd=d2lRVU9nYy9jNTM1dUE3VEJpSTJOZz09"
	# Holomorphic dynamics
	[1]="zoommtg://univ-tlse3-fr.zoom.us/join?action=join&confno=81730318623&pwd=TDdEaTlNSUNvNXBjSlRUZmVaREJ3UT09"
	# Learning
	[5]="zoommtg://zoom.us/join?action=join&confno=94751387445&pwd=aTFkTVcyeUxCcktRSTZwSDlEVTcxdz09"
)
# No more need zoom, our course is offline now.
#
# if [[ -z $zoom ]]; then
# 	echo -n "Open zoom automatically? "
# 	if read -q; then
# 		zoom=1
# 	fi
# fi
echo -n '\033[1;33m'
echo "\rCourse from $startdate to $enddate"
echo -n '\033[1;37m'
echo "DATE\tTIME\tInformation\n"
echo -n '\033[0m'
curl -s 'https://edt.univ-tlse3.fr/calendar2/Home/GetCalendarData' --data-raw "start=$startdate&end=$enddate&resType=103&calView=month&federationIds%5B%5D=28318&colourScheme=3" >/tmp/cour.json | jq -r 'sort_by(.start) | .[] | [.start, .description, .eventCategory, .end] | @tsv' |
	while IFS=$'\t' read -r starttime description eventCategory endtime; do
		if [[ $eventCategory = "CONGES" ]]; then
			continue
		fi
		if [[ $(date +%s) > $(date -d $endtime +%s) ]]; then
			continue
		fi
		# Color control events as yellow, and white otherwise
		if echo $eventCategory | sed -n '/control/I{q1}'; then
			echo -n '\033[0m'
		else
			echo -n '\033[1;33m'
		fi
		course_num=$(<<<$description | sed 's/.*Ri-basic course \([0-9]\).*/\1/p' -n)
		if [[ -n $course_num ]]; then
			# limit to only courses you follow
			if echo $follow_courses | grep -q $course_num; then
				echo -n $(date -d $starttime +"%a\t%H:%M\t")
				echo -n '\033[1;35m'
				echo -n $description | head -1
				echo -n "\b\t\t"
				echo -n '\033[0m'
				echo $course[$course_num]
				if [[ $zoom == 1 && $(date -I) == $(date -I -d $starttime) ]]; then # check zoom link
					if [[ $course_num == 2 ]]; then
						tmp1=${course_num}$(date +%a)
						xdg-open $zoomlink[$tmp1]
					else
						xdg-open $zoomlink[$course_num]
					fi
				fi
			fi
		else
			# I am PhD student now, I don't have seminars
			continue
			seminar_num=$(<<<$description | sed 's/.*seminar \([0-9]\).*/\1/p' -n)
			if [[ $seminar_num == 1 ]]; then
				echo -n $(date -d $starttime +"%a\t%H:%M\t")
				echo -n "Amphi Schwartz\t"
				echo $seminar[$seminar_num]
				if [[ $zoom == 1 && $(date -I) == $(date -I -d $starttime) ]]; then
					tmp2=${seminar_num}seminar
					xdg-open $zoomlink[$tmp2]
				fi
			fi
		fi
	done
