#!/bin/bash

Str=$(grep -i '^  opacity' /home/jing/Documents/Code/Shell/terminal/alacritty.yml)
echo "$Str" # debug
Str=${Str:11:5}
echo "$Str" # debug

step=0.05

case $1 in
"-dec")
	echo "Increasing opacity"
	num=$(awk "BEGIN {print $Str-$step; exit}")
	if (($(echo "$num < 0" | bc -l))); then
		num=0.0
	fi
	;;
"-inc")
	num=$(awk "BEGIN {print $Str+$step; exit}")
	if (($(echo "$num > 1" | bc -l))); then
		num=1.0
	fi
	;;
*)
	echo "Invalid option, use -inc or -dec flag."
	;;
esac

echo $num # debug

sed -i "s/^  opacity:.*/  opacity: $num/" /home/jing/Documents/Code/Shell/terminal/alacritty.yml
