#!/data/data/com.termux/files/usr/bin/sh

start_zerotier() {
	# Ping my own zerotier-one ip for testing
	ping -c 1 192.168.196.35 2>/dev/null 1>/dev/null
	if [ $? -ne 0 ]; then
		sudo ip rule | grep 'lookup main' 1>/dev/null
		if [ $? -ne 0 ]; then
			sudo ip rule add from all table main
		fi
		sudo zerotier-one &
	fi
}

start_atd() {
	pkill --signal 0 atd
	if [ $? -ne 0 ]; then
		atd
	fi
}

# wifi=$(su -c cmd wifi status | grep -oP 'Wifi is connected to "\K[^"]+')
ifconfig 2>/dev/null | grep 'inet 10.188' 1>/dev/null && ping -c 1 wireless.wifirst.net 2>/dev/null 1>/dev/null
if [ $? -eq 0 ]; then
	path_to_current_script=$HOME/.local/bin/wifirst
	queue=$(atq -q n)
	if [ $? -ne 0 ]; then
		rm -rf $PREFIX/var/spool/atd/*
	fi

	if [ ! -z "$queue" ]; then
		atq -q n | cut -f 1 | xargs atrm
	fi

	start_atd

	time_remaining=$(curl -s 'https://wireless.wifirst.net/captive-portal/api' -H "Content-Type: application/captive+json" | grep -oP '"seconds-remaining": \K\d+')
	if [ ${time_remaining:-0} -gt 10 ]; then
		at -q n -M -f $path_to_current_script now + $(expr $time_remaining / 60) minutes
		command -v sudo 2>/dev/null 1>/dev/null && start_zerotier
		exit
	fi

	curl -s 'https://wireless.wifirst.net/goform/HtmlLogout' \
		--data "error_url=https://www.google.fr" \
		--data "success_url=https://portal-front.wifirst.net"

	# Generate random account
	login_wifirst() {
		current_time=$(date +%s%3N)
		error_code=$(curl -s -D - 'https://wireless.wifirst.net/goform/HtmlLoginRequest' \
			--data "username=PAY/$current_time@wifirst.net" \
			--data "password=$current_time" \
			--data "success_url=https://www.google.fr" \
			--data "error_url=https://portal-front.wifirst.net" \
			--compressed | grep -o -P 'code=\K\d')
		return ${error_code:=0}
	}

	if ! login_wifirst; then
		if command -v sudo 2>/dev/null 1>/dev/null; then
			echo "Login failed, resetting MAC address"
			wifi=$(sudo cmd wifi status)
			current_ssid=$(echo $wifi | grep -o -P 'SSID: "\K.*(?=",)')
			su shell -c cmd wifi forget-network $(echo $wifi | grep -o -P 'Net ID: \K\d+')
			sudo cmd wifi connect-network "$current_ssid" open -r non_persistent
			sleep 8
			login_wifirst
		else
			echo "Please try to change MAC address from settings"
		fi
	fi
	at -q n -M -f $path_to_current_script now + 10 minute
else
	echo "Not connected to Wifirst"
fi

command -v sudo 2>/dev/null 1>/dev/null && start_zerotier

# vim: ft=zsh
